/**
 * Builds the universal Android APK, clearing Gradle's output first when the
 * version has changed since the last build.
 *
 * Gradle does not track `tauri.properties` as an input to its resource task, so
 * after a version bump an incremental build reuses the previous manifest and
 * produces an APK that still declares the old versionName — a package that says
 * 0.1.0 inside a release called 0.1.1. It happens in both directions. Packaging
 * catches it afterwards with aapt2 (D-085), but only after a ten-minute build
 * has already been spent, and the remedy is not obvious from the error unless
 * you already know about the missing input.
 *
 * `tauri.properties` is regenerated by the Tauri CLI during the build, so before
 * one runs it still holds the version the last build used. Comparing it to
 * package.json is therefore exactly the question "did the version change since
 * the last build", and clearing on a difference costs nothing when it has not.
 * See D-087.
 */
import fs from "node:fs";
import path from "node:path";
import { spawnSync } from "node:child_process";

const rootDir = process.cwd();
const VERSION = JSON.parse(
  fs.readFileSync(path.resolve(rootDir, "package.json"), "utf-8")
).version;

const gradleBuildDir = path.resolve(rootDir, "src-tauri/gen/android/app/build");
const propsPath = path.resolve(rootDir, "src-tauri/gen/android/app/tauri.properties");

let lastBuilt = null;
if (fs.existsSync(propsPath)) {
  const props = fs.readFileSync(propsPath, "utf-8");
  lastBuilt = (props.match(/tauri\.android\.versionName=(.+)/) || [])[1]?.trim() ?? null;
}

if (lastBuilt !== null && lastBuilt !== VERSION && fs.existsSync(gradleBuildDir)) {
  console.log(
    `  › Version changed since the last Android build (${lastBuilt} → ${VERSION}).`
  );
  console.log("    Clearing Gradle output so the manifest is regenerated.");
  fs.rmSync(gradleBuildDir, { recursive: true, force: true });
} else if (lastBuilt === null) {
  console.log("  › No previous Android build recorded; building from scratch.");
} else {
  console.log(`  › Version unchanged since the last Android build (${VERSION}).`);
}

const args = ["tauri", "android", "build", "--target", "aarch64", "armv7", "x86_64", "--apk"];
const result = spawnSync("cargo", args, { stdio: "inherit", shell: process.platform === "win32" });
process.exit(result.status ?? 1);
